<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AlternatifSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $L = 'Laki-laki';
        $P = 'Perempuan';

        $alternatif = [
            [
                'kode_alternatif' => 'A1',
                'nama_alternatif' => 'Mary Wahyuningsih, S.Kom',
                'jenis_kelamin' => $P,
                'tanggal_masuk_kerja' => '2001-07-01',
                'nip' => '0101001',
                'jabatan' => 'Deputi 1',
                'pendidikan' => 'S1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A2',
                'nama_alternatif' => 'Lucia Sutarni, S.Pd',
                'jenis_kelamin' => $P,
                'tanggal_masuk_kerja' => '2004-07-01',
                'nip' => '0402002',
                'jabatan' => 'Kepala Sekolah TK',
                'pendidikan' => 'S1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A3',
                'nama_alternatif' => 'Irmina Sihura',
                'jenis_kelamin' => $P,
                'tanggal_masuk_kerja' => '2005-07-01',
                'nip' => '0502003',
                'jabatan' => 'Guru',
                'pendidikan' => 'D3',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A4',
                'nama_alternatif' => 'Rita Sofiani',
                'jenis_kelamin' => $P,
                'tanggal_masuk_kerja' => '2006-04-01',
                'nip' => '0604004',
                'jabatan' => 'Tata Usaha',
                'pendidikan' => 'SMA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A5',
                'nama_alternatif' => 'Hendriette Aphrodite Naomi Angelique Salakory',
                'jenis_kelamin' => $P,
                'tanggal_masuk_kerja' => '2006-07-01',
                'nip' => '0602005',
                'jabatan' => 'Guru',
                'pendidikan' => 'PGTK',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A6',
                'nama_alternatif' => 'Tiyas Wulandari, S.Psi',
                'jenis_kelamin' => $P,
                'tanggal_masuk_kerja' => '2008-07-01',
                'nip' => '0802008',
                'jabatan' => 'Guru',
                'pendidikan' => 'S1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A7',
                'nama_alternatif' => 'Selamat, M.Pd',
                'jenis_kelamin' => $L,
                'tanggal_masuk_kerja' => '2009-07-01',
                'nip' => '0901009',
                'jabatan' => 'Deputi 2',
                'pendidikan' => 'S2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A8',
                'nama_alternatif' => 'Tek Hok, S.Kom',
                'jenis_kelamin' => $L,
                'tanggal_masuk_kerja' => '2010-01-01',
                'nip' => '1002016',
                'jabatan' => 'Guru',
                'pendidikan' => 'S1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A9',
                'nama_alternatif' => 'Leni Sihombing, S.Pd',
                'jenis_kelamin' => $P,
                'tanggal_masuk_kerja' => '2010-07-01',
                'nip' => '1002018',
                'jabatan' => 'Guru',
                'pendidikan' => 'S1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A10',
                'nama_alternatif' => 'Diyah Kartika S,S.H',
                'jenis_kelamin' => $P,
                'tanggal_masuk_kerja' => '2011-07-01',
                'nip' => '1102026',
                'jabatan' => 'Guru',
                'pendidikan' => 'S1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A11',
                'nama_alternatif' => 'Muddin Sidabalok, S.Pd',
                'jenis_kelamin' => $L,
                'tanggal_masuk_kerja' => '2011-07-01',
                'nip' => '1102030',
                'jabatan' => 'Guru',
                'pendidikan' => 'S1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A12',
                'nama_alternatif' => 'Ninik Kristoermadiarsih, M.M',
                'jenis_kelamin' => $P,
                'tanggal_masuk_kerja' => '2011-10-17',
                'nip' => '1102035',
                'jabatan' => 'Kepala Sekolah SD',
                'pendidikan' => 'S2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A13',
                'nama_alternatif' => 'Christina Puloraran',
                'jenis_kelamin' => $P,
                'tanggal_masuk_kerja' => '2012-01-25',
                'nip' => '1202040',
                'jabatan' => 'Guru',
                'pendidikan' => 'PGTK',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A14',
                'nama_alternatif' => 'Triyono, S.E, M.Div',
                'jenis_kelamin' => $L,
                'tanggal_masuk_kerja' => '2012-07-01',
                'nip' => '1202043',
                'jabatan' => 'Kerohanian',
                'pendidikan' => 'S2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A15',
                'nama_alternatif' => 'Tanasia. S.Th',
                'jenis_kelamin' => $P,
                'tanggal_masuk_kerja' => '2012-07-01',
                'nip' => '1202044',
                'jabatan' => 'Guru',
                'pendidikan' => 'S2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A16',
                'nama_alternatif' => 'Lusiana Sele, S.Pd',
                'jenis_kelamin' => $P,
                'tanggal_masuk_kerja' => '2012-07-01',
                'nip' => '1202047',
                'jabatan' => 'Guru',
                'pendidikan' => 'S1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A17',
                'nama_alternatif' => 'Iria Kharisma Joseph, ST',
                'jenis_kelamin' => $L,
                'tanggal_masuk_kerja' => '2012-07-01',
                'nip' => '1202049',
                'jabatan' => 'Guru',
                'pendidikan' => 'S1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A18',
                'nama_alternatif' => 'Lisa Julita Mokosandi, S.Th',
                'jenis_kelamin' => $P,
                'tanggal_masuk_kerja' => '2013-07-01',
                'nip' => '1302072',
                'jabatan' => 'Guru',
                'pendidikan' => 'S1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A19',
                'nama_alternatif' => 'Theresia Rusmiyati',
                'jenis_kelamin' => $P,
                'tanggal_masuk_kerja' => '2013-07-01',
                'nip' => '1302075',
                'jabatan' => 'Guru',
                'pendidikan' => 'D3',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A20',
                'nama_alternatif' => 'Elna Santosa Manuel',
                'jenis_kelamin' => $P,
                'tanggal_masuk_kerja' => '2013-07-01',
                'nip' => '1304077',
                'jabatan' => 'Tata Usaha',
                'pendidikan' => 'SMA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A21',
                'nama_alternatif' => 'Yacobus Santana, S.Pd',
                'jenis_kelamin' => $L,
                'tanggal_masuk_kerja' => '2014-07-01',
                'nip' => '1402085',
                'jabatan' => 'Guru',
                'pendidikan' => 'S1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A22',
                'nama_alternatif' => 'R.AB.Susi Hastono, S.E',
                'jenis_kelamin' => $L,
                'tanggal_masuk_kerja' => '2014-07-01',
                'nip' => '1402087',
                'jabatan' => 'Guru',
                'pendidikan' => 'S1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A23',
                'nama_alternatif' => 'Marusaha Samosir, S.Pd',
                'jenis_kelamin' => $L,
                'tanggal_masuk_kerja' => '2014-07-01',
                'nip' => '1402089',
                'jabatan' => 'Guru',
                'pendidikan' => 'S1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A24',
                'nama_alternatif' => 'Aprilliana Grace Wilma Thenu, S.Sos',
                'jenis_kelamin' => $P,
                'tanggal_masuk_kerja' => '2014-07-01',
                'nip' => '1402092',
                'jabatan' => 'Guru',
                'pendidikan' => 'S1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A25',
                'nama_alternatif' => 'Gani Praditja Sakti, S.Pd',
                'jenis_kelamin' => $L,
                'tanggal_masuk_kerja' => '2015-07-01',
                'nip' => '1502101',
                'jabatan' => 'Guru',
                'pendidikan' => 'S1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A26',
                'nama_alternatif' => 'Fransisca X.Suharti, S.Pd',
                'jenis_kelamin' => $L,
                'tanggal_masuk_kerja' => '2015-07-01',
                'nip' => '1502104',
                'jabatan' => 'Guru',
                'pendidikan' => 'S1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A27',
                'nama_alternatif' => 'Kristiani Dwi Nugrohowati Djatiningsih, S.E',
                'jenis_kelamin' => $P,
                'tanggal_masuk_kerja' => '2015-10-01',
                'nip' => '1502107',
                'jabatan' => 'Guru',
                'pendidikan' => 'S1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A28',
                'nama_alternatif' => 'Elisabeth, S.Pd',
                'jenis_kelamin' => $P,
                'tanggal_masuk_kerja' => '2016-07-01',
                'nip' => '1602108',
                'jabatan' => 'Guru',
                'pendidikan' => 'S1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A29',
                'nama_alternatif' => 'Sovia Nainggolan, M.Pd',
                'jenis_kelamin' => $P,
                'tanggal_masuk_kerja' => '2016-07-01',
                'nip' => '1602111',
                'jabatan' => 'Kepala Sekolah SMP',
                'pendidikan' => 'S2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A30',
                'nama_alternatif' => 'Cornelius Wiwit, S.Pd',
                'jenis_kelamin' => $L,
                'tanggal_masuk_kerja' => '2016-07-01',
                'nip' => '1602112',
                'jabatan' => 'Guru',
                'pendidikan' => 'S1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A31',
                'nama_alternatif' => 'Artha Maulina Rochendraty, S.Pd',
                'jenis_kelamin' => $P,
                'tanggal_masuk_kerja' => '2016-07-01',
                'nip' => '1602123',
                'jabatan' => 'Guru',
                'pendidikan' => 'S1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A32',
                'nama_alternatif' => 'Siti Limaria Silaban, S.Pd',
                'jenis_kelamin' => $P,
                'tanggal_masuk_kerja' => '2016-07-01',
                'nip' => '1602125',
                'jabatan' => 'Guru',
                'pendidikan' => 'S1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A33',
                'nama_alternatif' => 'Steven Evan Edifianto, S.Pd',
                'jenis_kelamin' => $L,
                'tanggal_masuk_kerja' => '2016-07-01',
                'nip' => '1602126',
                'jabatan' => 'Guru',
                'pendidikan' => 'S1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A34',
                'nama_alternatif' => 'Delinda',
                'jenis_kelamin' => $P,
                'tanggal_masuk_kerja' => '2016-07-01',
                'nip' => '1604128',
                'jabatan' => 'Tata Usaha',
                'pendidikan' => 'SMA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A35',
                'nama_alternatif' => 'Linda Tiur Mauly, M.M',
                'jenis_kelamin' => $P,
                'tanggal_masuk_kerja' => '2017-07-01',
                'nip' => '1702138',
                'jabatan' => 'Guru',
                'pendidikan' => 'S2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A36',
                'nama_alternatif' => 'Jaka Winarta,M.Div',
                'jenis_kelamin' => $L,
                'tanggal_masuk_kerja' => '2017-07-01',
                'nip' => '1702139',
                'jabatan' => 'Kerohanian',
                'pendidikan' => 'S2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A37',
                'nama_alternatif' => 'Heri Prasetya, S.Pd',
                'jenis_kelamin' => $L,
                'tanggal_masuk_kerja' => '2018-07-01',
                'nip' => '1802143',
                'jabatan' => 'Guru',
                'pendidikan' => 'S1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A38',
                'nama_alternatif' => 'Martha Septiningtyas, S.Pd, M.Hum.',
                'jenis_kelamin' => $P,
                'tanggal_masuk_kerja' => '2018-07-01',
                'nip' => '1802145',
                'jabatan' => 'Guru',
                'pendidikan' => 'S2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A39',
                'nama_alternatif' => 'Pesta Maria Siburian, S.Pd',
                'jenis_kelamin' => $P,
                'tanggal_masuk_kerja' => '2019-07-01',
                'nip' => '1902151',
                'jabatan' => 'Guru',
                'pendidikan' => 'S1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A40',
                'nama_alternatif' => 'Ronica Sales Julianti Siahaan, S.Pd',
                'jenis_kelamin' => $P,
                'tanggal_masuk_kerja' => '2019-07-01',
                'nip' => '1902152',
                'jabatan' => 'Guru',
                'pendidikan' => 'S1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A41',
                'nama_alternatif' => 'Roslinah, S.Pd',
                'jenis_kelamin' => $P,
                'tanggal_masuk_kerja' => '2019-07-01',
                'nip' => '1902154',
                'jabatan' => 'Guru',
                'pendidikan' => 'S1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A42',
                'nama_alternatif' => 'Elvina Br. Manik, S.Pd',
                'jenis_kelamin' => $P,
                'tanggal_masuk_kerja' => '2020-07-01',
                'nip' => '2002161',
                'jabatan' => 'Guru',
                'pendidikan' => 'S1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A43',
                'nama_alternatif' => 'Rian Hendri Tupamahu, S.Pd',
                'jenis_kelamin' => $L,
                'tanggal_masuk_kerja' => '2020-07-01',
                'nip' => '2002163',
                'jabatan' => 'Guru',
                'pendidikan' => 'S1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A44',
                'nama_alternatif' => 'Rachel Oktaviani Hutahaean, S.Pd',
                'jenis_kelamin' => $P,
                'tanggal_masuk_kerja' => '2021-01-01',
                'nip' => '2102164',
                'jabatan' => 'Guru',
                'pendidikan' => 'S1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A45',
                'nama_alternatif' => 'Prima Caesar, B.Ed, S.Pd.',
                'jenis_kelamin' => $P,
                'tanggal_masuk_kerja' => '2020-07-01',
                'nip' => '2102165',
                'jabatan' => 'Guru',
                'pendidikan' => 'S1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A46',
                'nama_alternatif' => 'Dhea Khanti Nathali',
                'jenis_kelamin' => $P,
                'tanggal_masuk_kerja' => '2021-10-01',
                'nip' => '2102166',
                'jabatan' => 'Tata Usaha',
                'pendidikan' => 'S1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A47',
                'nama_alternatif' => 'Jelda Febrina Sesfaot, S.Pd',
                'jenis_kelamin' => $P,
                'tanggal_masuk_kerja' => '2021-01-01',
                'nip' => '2102167',
                'jabatan' => 'Guru',
                'pendidikan' => 'S1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A48',
                'nama_alternatif' => 'Romi Poire Sihotang, S.Kom',
                'jenis_kelamin' => $L,
                'tanggal_masuk_kerja' => '2022-01-01',
                'nip' => '2102168',
                'jabatan' => 'Guru',
                'pendidikan' => 'S1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A49',
                'nama_alternatif' => 'Sriningsih Hutabarat, S.Pd',
                'jenis_kelamin' => $P,
                'tanggal_masuk_kerja' => '2023-07-01',
                'nip' => '2307201',
                'jabatan' => 'Guru',
                'pendidikan' => 'S1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A50',
                'nama_alternatif' => 'Theresa Christina Yoel, S.Pd',
                'jenis_kelamin' => $P,
                'tanggal_masuk_kerja' => '2023-07-01',
                'nip' => '2307202',
                'jabatan' => 'Guru',
                'pendidikan' => 'S1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A51',
                'nama_alternatif' => 'Erni Maduma BR Marbun, S.Pd',
                'jenis_kelamin' => $P,
                'tanggal_masuk_kerja' => '2023-07-01',
                'nip' => '2307203',
                'jabatan' => 'Guru',
                'pendidikan' => 'S1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A52',
                'nama_alternatif' => 'Tanty Chandra Siregar, S.Pd',
                'jenis_kelamin' => $P,
                'tanggal_masuk_kerja' => '2023-07-01',
                'nip' => '2307204',
                'jabatan' => 'Guru',
                'pendidikan' => 'S1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A53',
                'nama_alternatif' => 'Agnes Paul, S.Pd',
                'jenis_kelamin' => $P,
                'tanggal_masuk_kerja' => '2023-07-01',
                'nip' => '2307205',
                'jabatan' => 'Guru',
                'pendidikan' => 'S1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A54',
                'nama_alternatif' => 'Missy Friska Margaretha',
                'jenis_kelamin' => $P,
                'tanggal_masuk_kerja' => '2024-04-17',
                'nip' => '2407209',
                'jabatan' => 'Guru',
                'pendidikan' => 'S1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A55',
                'nama_alternatif' => 'Andre Saputra Julianto',
                'jenis_kelamin' => $L,
                'tanggal_masuk_kerja' => '2024-04-22',
                'nip' => '2407210',
                'jabatan' => 'Guru',
                'pendidikan' => 'S1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A56',
                'nama_alternatif' => 'Yeny Irawati',
                'jenis_kelamin' => $P,
                'tanggal_masuk_kerja' => '2024-06-01',
                'nip' => '2402211',
                'jabatan' => 'Tata Usaha',
                'pendidikan' => 'S1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A57',
                'nama_alternatif' => 'Ekam Sehari Manalu',
                'jenis_kelamin' => $L,
                'tanggal_masuk_kerja' => '2024-07-01',
                'nip' => '2407212',
                'jabatan' => 'Guru',
                'pendidikan' => 'S1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_alternatif' => 'A58',
                'nama_alternatif' => 'Odaligo Zega',
                'jenis_kelamin' => $L,
                'tanggal_masuk_kerja' => '2024-07-01',
                'nip' => '2407213',
                'jabatan' => 'Guru',
                'pendidikan' => 'S1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($alternatif as $data) {
            \App\Models\Alternatif::create($data);
        }
    }
}
