<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SkalaIndikatorDetailSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $skalaIndikatorDetail = [
            [
                'id_skala_indikator' => 1,
                'skala' => '1',
                'deskripsi_skala' => 'Tidak mengakui kesalahan, menutupi informasi/kejadian. Melemparkan kesalahan/tanggung jawab kepada orang lain.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 1,
                'skala' => '2',
                'deskripsi_skala' => 'Mengakui kesalahan karena terpaksa, bukan atas inisiatif sendiri; melibatkan pihak lain untuk ikut bertanggung jawab atas masalah.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 1,
                'skala' => '3',
                'deskripsi_skala' => 'Jujur, mengakui kesalahan dengan segera, tidak menutupi informasi/ kejadian dan bersedia menanggung konsekuensi yang terjadi.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 1,
                'skala' => '4',
                'deskripsi_skala' => 'Terbuka terhadap fakta, informasi, kejadian. Sangat minim melakukan kesalahan karena menjalankan nilai Alkitab dengan konsisten.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 2,
                'skala' => '1',
                'deskripsi_skala' => 'Melakukan cara atau tindakan yang bertentangan dengan aturan instansi secara sengaja.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 2,
                'skala' => '2',
                'deskripsi_skala' => 'Mengambil keputusan/bertindak berdasarkan suatu kejadian saja tanpa mengacu aturan/ prosedur instansi.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 2,
                'skala' => '3',
                'deskripsi_skala' => 'Mengambil keputusan/bertindak sesuai dengan aturan/prosedur instansi dengan mempertimbangkan konteks.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 2,
                'skala' => '4',
                'deskripsi_skala' => 'Mengambil keputusan sesuai aturan/prosedur instansi dengan mempertimbangkan konteks dan tanggung jawab serta nilai moral/etika.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 3,
                'skala' => '1',
                'deskripsi_skala' => 'Menghindari konflik, tidak bersedia terlibat situasi/tanggung jawab yang berpotensi terjadi konflik. Meniadakan konflik, tidak mau menghadapinya.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 3,
                'skala' => '2',
                'deskripsi_skala' => 'Membutuhkan bantuan solusi dan pendampingan dari atasan/rekan kerja untuk menyelesaikan konflik.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 3,
                'skala' => '3',
                'deskripsi_skala' => 'Menghadapi pihak lain yang terlibat konflik dengan terbuka dan menemukan win-win solution meskipun masih memerlukan pendampingan/mediasi.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 3,
                'skala' => '4',
                'deskripsi_skala' => 'Mampu memahami kepentingan pihak lain yang terlibat konflik, dan mampu menyelesaikan secara mandiri bersama pihak terkait selaras dengan nilai dan etika.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 4,
                'skala' => '1',
                'deskripsi_skala' => 'Belum menunjukkan inisiatif dalam mengerjakan tugas, mengalami kesulitan memenuhi standar dan batas waktu yang ditetapkan.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 4,
                'skala' => '2',
                'deskripsi_skala' => 'Ada insiatif untuk mengerjakan tugas dan mencari bantuan, namun membutuhkan pendampingan/
pengawasan agar selesai sesuai standar.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 4,
                'skala' => '3',
                'deskripsi_skala' => 'Dapat menyelesaikan tugasnya dengan pengawasan yang minimal sesuai dengan standar dan batas waktu.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 4,
                'skala' => '4',
                'deskripsi_skala' => 'Dapat menyelesaikan tugasnya dengan pengawasan yang minimal sesuai dengan standar dan batas waktu.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 5,
                'skala' => '1',
                'deskripsi_skala' => 'Tidak mengetahui visi instansi.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 5,
                'skala' => '2',
                'deskripsi_skala' => 'Dapat menyebutkan visi instansi namun belum mengenali penerapannya dalam lingkup tugas sehari-hari.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 5,
                'skala' => '3',
                'deskripsi_skala' => 'Dapat menyampaikan visi instansi dengan kontekstual dalam kegiatan kerja sehari-hari.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 5,
                'skala' => '4',
                'deskripsi_skala' => 'Memahami visi instansi dan mampu menerapkan secara komprehensif dalam pekerjaan sehari-hari.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 6,
                'skala' => '1',
                'deskripsi_skala' => 'Enggan untuk memberikan pertolongan; bersedia memberikan bantuan terbatas saat ditugaskan oleh atasan.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 6,
                'skala' => '2',
                'deskripsi_skala' => 'Bersedia memberikan bantuan apabila ada pihak yang meminta.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 6,
                'skala' => '3',
                'deskripsi_skala' => 'Menunjukkan inisiatif untuk menawarkan bantuan kepada sesama rekan kerja maupun siswa.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 6,
                'skala' => '4',
                'deskripsi_skala' => 'Proaktif untuk menawarkan bantuan dan mampu menyesuaikan bentuk/jenis bantuan bagi rekan kerja/siswa secara spesifik.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 7,
                'skala' => '1',
                'deskripsi_skala' => 'Tidak memberikan kesempatan bagi siswa/rekan kerja untuk belajar/melakukan hal baru.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 7,
                'skala' => '2',
                'deskripsi_skala' => 'Memberikan pendampingan/melatih siswa/rekan kerja dengan sporadis, untuk situasi tertentu.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 7,
                'skala' => '3',
                'deskripsi_skala' => 'Mengenali minat/potensi rekan kerja/siswa dan memberikan kesempatan belajar melalui penugasan dan pendampingan.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 7,
                'skala' => '4',
                'deskripsi_skala' => 'Mampu bertindak sebagai mentor bagi siswa/rekan melalui bantuan/pen dampingan terencana dalam kurun waktu tertentu.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 8,
                'skala' => '1',
                'deskripsi_skala' => 'Bersikap berdasarkan suasana hati tanpa memperhatikan situasi, menunjukkan sikap/ tindakan berdasarkan status/golongan seseorang.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 8,
                'skala' => '2',
                'deskripsi_skala' => 'Memberikan tanggapan dan bersikap seadanya, sebatas tuntutan yang menjadi aturan instansi.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 8,
                'skala' => '3',
                'deskripsi_skala' => 'Dapat berinteraksi dengan orang lain sesuai situasi dengan memperhatikan sopan santun.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 8,
                'skala' => '4',
                'deskripsi_skala' => 'Bertindak/ bercakap dengan menghargai dan peka terhadap keadaan orang lain serta mampu melakukan penyesuaian yang diperlukan.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 9,
                'skala' => '1',
                'deskripsi_skala' => 'Menolak umpan balik yang diberikan oleh pihak lain.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 9,
                'skala' => '2',
                'deskripsi_skala' => 'Menjalankan umpan balik apabila hal tersebut diwajibkan instansi atau mempengaruhi hasil kerja.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 9,
                'skala' => '3',
                'deskripsi_skala' => 'Bersikap terbuka dan menghargai pendapat/ masukan orang lain serta menjalankan perbaikan berdasarkan hal tersebut.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 9,
                'skala' => '4',
                'deskripsi_skala' => 'Proaktif mencari umpan balik/masukan terhadap hasil kerja maupun kegiatan yang dilakukan, terutama dari orang lain yang lebih ahli dalam bidang tsb dan bersedia menjalankannya.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 10,
                'skala' => '1',
                'deskripsi_skala' => 'Melakukan tindakan/perbuatan yang membahayakan dan mengotori lingkungan.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 10,
                'skala' => '2',
                'deskripsi_skala' => 'Menjaga kebersihan lingkungan yang berada langsung dalam lingkup kerjanya.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 10,
                'skala' => '3',
                'deskripsi_skala' => 'Menjaga kebersihan area sekolah dan tempat tinggal serta memberikan cara-cara praktis bagi siswa dan rekan kerja untuk melakukan hal yang sama.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 10,
                'skala' => '4',
                'deskripsi_skala' => 'Melakukan cara-cara yang terarah untuk mengedukasi siswa dan rekan kerja menjaga kelestarian lingkungan sekitar.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 11,
                'skala' => '1',
                'deskripsi_skala' => 'Menyapa, memberi salam dan mengajak berdoa yang dipimpin oleh siswa.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 11,
                'skala' => '2',
                'deskripsi_skala' => 'Menyapa, memberi salam, mengajak berdoa dan mengajukan beberapa pertanyaan berkaitan materi yang sudah dipelajari.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 11,
                'skala' => '3',
                'deskripsi_skala' => 'Menyapa, memberi salam, mengajak berdoa dan mengajukan beberapa pertanyaan berkaitan materi yang sudah dipelajari dan menyampaikan rencana kegiatan pembelajaran yang akan dipelajari.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 11,
                'skala' => '4',
                'deskripsi_skala' => 'Menyapa, memberi salam, mengajak berdoa dan mengajukan beberapa pertanyaan berkaitan materi yang sudah dipelajari dan menyampaikan rencana kegiatan pembelajaran yang akan dipelajari dengan menggunakan media kreatif.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 12,
                'skala' => '1',
                'deskripsi_skala' => 'Mengajukan pertanyaan pemantik.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 12,
                'skala' => '2',
                'deskripsi_skala' => 'Mengajukan pertanyaan pemantik yang menantang dan membangun motivasi siswa.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 12,
                'skala' => '3',
                'deskripsi_skala' => 'Mengajukan pertanyaan pemantik yang menantang dan membangun motivasi siswa dan menyampaikan manfaat hal yang akan dipelajari dalam kehidupan sehari-hari.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 12,
                'skala' => '4',
                'deskripsi_skala' => 'Mengajukan pertanyaan pemantik yang menantang, membangun motivasi siswa dan menyampaikan manfaat hal yang akan dipelajari dalam kehidupan sehari-hari dengan menggunakan media kreatif.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 13,
                'skala' => '1',
                'deskripsi_skala' => 'Menyampaikan capaian dan tujuan pembelajaran.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 13,
                'skala' => '2',
                'deskripsi_skala' => 'Menyampaikan capaian, tujuan pembelajaran dengan mengaitkan materi pembelajaran dengan materi sebelumnya.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 13,
                'skala' => '3',
                'deskripsi_skala' => 'Menyampaikan capaian, tujuan pembelajaran dan mengaitkan materi pembelajaran dengan materi sebelumnya serta mampu mengarahkan siswa fokus pada materi yang diajarkan.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 13,
                'skala' => '4',
                'deskripsi_skala' => 'Menyampaikan capaian, tujuan pembelajaran dan mengaitkan materi pembelajaran dengan materi sebelumnya serta mampu mengarahkan siswa fokus pada materi yang diajarkan dengan mengenal emosi siswa.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 14,
                'skala' => '1',
                'deskripsi_skala' => 'Menyampaikan topik materi ajar dan pertanyaan pemantik.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 14,
                'skala' => '2',
                'deskripsi_skala' => 'Menyampaikan topik materi ajar, pertanyaan pemantik, mencari jawaban pertanyaan pemantik dengan pengetahuan lain yang relevan, perkembangan IPTEK, budaya positif dan kehidupan nyata.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 14,
                'skala' => '3',
                'deskripsi_skala' => 'Menyampaikan topik materi ajar, pertanyaan pemantik, mencari jawaban pertanyaan pemantik dengan pengetahuan lain yang relevan, perkembangan IPTEK, budaya positif dan kehidupan nyata dan menyajikan pembahasan materi pembelajaran yang tepat secara sistematis.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 14,
                'skala' => '4',
                'deskripsi_skala' => 'Menyampaikan topik materi ajar, pertanyaan pemantik, mencari jawaban pertanyaan pemantik dengan pengetahuan lain yang relevan, perkembangan IPTEK, budaya positif dan kehidupan nyata dan menyajikan pembahasan materi pembelajaran yang tepat secara sistematis dengan menggunakan media kreatif.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 15,
                'skala' => '1',
                'deskripsi_skala' => 'Melaksanakan pembelajaran sesuai dengan kompetensi yang akan dicapai.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 15,
                'skala' => '2',
                'deskripsi_skala' => 'Melaksanakan pembelajaran sesuai dengan kompetensi yang akan dicapai dengan membentuk kelompok siswa berdasarkan kriteria gaya belajar.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 15,
                'skala' => '3',
                'deskripsi_skala' => 'Melaksanakan pembelajaran sesuai dengan kompetensi yang akan dicapai dengan membentuk kelompok siswa berdasarkan kriteria gaya belajar yang menumbuhkan dan mengembangkan keterampilan, kebiasaan dan sikap positif.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 15,
                'skala' => '4',
                'deskripsi_skala' => 'Melaksanakan pembelajaran sesuai dengan kompetensi yang akan dicapai dengan membentuk kelompok siswa berdasarkan kriteria gaya belajar yang menumbuhkan dan mengembangkan keterampilan, kebiasaan dan sikap positif, sesuai alokasi waktu yang direncanakan.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 16,
                'skala' => '1',
                'deskripsi_skala' => 'melaksanakan pembelajaran yang menumbuhkan partisipasi aktif.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 16,
                'skala' => '2',
                'deskripsi_skala' => 'Melaksanakan pembelajaran yang menumbuhkan partisipasi aktif dalam diskusi kelompok.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 16,
                'skala' => '3',
                'deskripsi_skala' => 'Melaksanakan pembelajaran yang menumbuhkan partisipasi aktif dalam diskusi kelompok serta mempresentasikan hasil diskusi.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 16,
                'skala' => '4',
                'deskripsi_skala' => 'Melaksanakan pembelajaran yang menumbuhkan partisipasi aktif dalam diskusi kelompok dan mempresentasikan hasil diskusi serta menghasilkan karya tulis/ produk.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 17,
                'skala' => '1',
                'deskripsi_skala' => 'Melaksanakan pembelajaran yang mengasah kreatif dan kritis siswa.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 17,
                'skala' => '2',
                'deskripsi_skala' => 'Melaksanakan pembelajaran yang mengasah kreativitas, menumbuhkan pemikiran yang kritis dan mampu mengomunikasikan materi yang didapat saat pembelajaran.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 17,
                'skala' => '3',
                'deskripsi_skala' => 'Melaksanakan pembelajaran yang mengasah kreativitas, menumbuhkan pemikiran yang kritis, mengomunikasikan serta mampu berkolaborasi antar siswa sesuai materi yang didapat saat pembelajaran.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 17,
                'skala' => '4',
                'deskripsi_skala' => 'Melaksanakan pembelajaran yang mengasah kreativitas, menumbuhkan pemikiran yang kritis, mengomunikasikan serta mampu berkolaborasi antar siswa sesuai materi yang didapat saat pembelajaran dengan menggunakan berbagai media belajar.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 18,
                'skala' => '1',
                'deskripsi_skala' => 'Menciptakan suasana kelas yang kondusif untuk proses belajar mengajar.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 18,
                'skala' => '2',
                'deskripsi_skala' => 'Menciptakan suasana kelas yang kondusif dengan menerapkan prinsip disiplin positif untuk proses belajar mengajar.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 18,
                'skala' => '3',
                'deskripsi_skala' => 'Menciptakan suasana kelas yang kondusif dengan menerapkan prinsip disiplin positif untuk membentuk perilaku adaptif yang telah disepakati dalam proses belajar mengajar.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 18,
                'skala' => '4',
                'deskripsi_skala' => 'Menciptakan suasana kelas yang kondusif dengan menerapkan prinsip disiplin positif untuk membentuk perilaku adaptif yang telah disepakati dan menuliskan komitmen kelas dalam proses belajar mengajar.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 19,
                'skala' => '1',
                'deskripsi_skala' => 'Mengomunikasikan pesan bahwa guru percaya akan kemampuan semua murid untuk belajar dan berprestasi secara akademik.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 19,
                'skala' => '2',
                'deskripsi_skala' => 'Mengomunikasikan pesan bahwa guru percaya akan kemampuan semua murid untuk belajar, member I perhatian dan bantuan ekstra sesuai kebutuhan belajar setiap siswa.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 19,
                'skala' => '3',
                'deskripsi_skala' => 'Mengomunikasikan pesan bahwa guru percaya akan kemampuan semua murid untuk belajar, memberi perhatian, bantuan ekstra, melakukan evaluasi dan motivasi sesuai kebutuhan belajar.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 19,
                'skala' => '4',
                'deskripsi_skala' => 'Mengomunikasikan pesan bahwa guru percaya akan kemampuan semua murid untuk belajar, memberi perhatian, bantuan ekstra, melakukan evaluasi dan motivasi sesuai kebutuhan belajar setiap dan membuat rubrik prestasi belajar.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 20,
                'skala' => '1',
                'deskripsi_skala' => 'melaksanakan praktik adaptasi pengajaran sebagai respon atas umpan balik dan respon murid terhadap kebutuhan belajarnya.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 20,
                'skala' => '2',
                'deskripsi_skala' => 'Melaksanakan praktik adaptasi pengajaran sebagai respon atas umpan balik terhadap kebutuhan belajarnya dan memberi konten materi berbeda dalam capaian pembelajaran yang sama.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 20,
                'skala' => '3',
                'deskripsi_skala' => 'Melaksanakan praktik adaptasi pengajaran sebagai respon atas umpan balik dan respon murid terhadap kebutuhan belajarnya dan member konten materi berbeda dalam capaian pembelajaran yang sama di beberapa kelompok yang berbeda dan mampu menerapkan serta berkolaborasi dalam memaknai materi ajar.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 20,
                'skala' => '4',
                'deskripsi_skala' => 'Melaksanakan praktik adaptasi pengajaran sebagai respon atas umpan balik dan respon murid terhadap kebutuhan belajarnya dan member konten materi berbeda dalam capaian pembelajaran yang sama di beberapa kelompok yang berbeda dan mampu menerapka serta berkolaborasi dalam memaknai materi ajar dalam setiap pembelajaran.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 21,
                'skala' => '1',
                'deskripsi_skala' => 'Menunjukkan keterampilan dalam penggunaan sumber belajar yang bervariasi.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 21,
                'skala' => '2',
                'deskripsi_skala' => 'Menunjukkan keterampilan dalam penggunaan sumber belajar, media yang bervariasi yaitu visual dan audio.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 21,
                'skala' => '3',
                'deskripsi_skala' => 'Menunjukkan keterampilan dalam penggunaan sumber belajar, media yang bervariasi yaitu visual, Audio dan kinestetik.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 21,
                'skala' => '4',
                'deskripsi_skala' => 'Menunjukkan keterampilan dalam penggunaan sumber belajar, media yang bervariasi yaitu visual, Audio dan kinestetik yang menarik.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 22,
                'skala' => '1',
                'deskripsi_skala' => 'Membawa alat peraga dalam kelas.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 22,
                'skala' => '2',
                'deskripsi_skala' => 'Membawa alat peraga dalam kelas dan menggunakannya saat pembelajaran.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 22,
                'skala' => '3',
                'deskripsi_skala' => 'Membawa alat peraga dalam kelas dan menggunakannya saat pembelajaran serta melibatkan siswa dalam menggunakan alat tersebut.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 22,
                'skala' => '4',
                'deskripsi_skala' => 'Membawa alat peraga dalam kelas, menggunakannya saat pembelajaran dan melibatkan siswa dalam menggunakan alat tersebut serta dapat membuat alat peraga sendiri.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 23,
                'skala' => '1',
                'deskripsi_skala' => 'Dapat menggunakan bahasa lisan secara jelas dan lancar.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 23,
                'skala' => '2',
                'deskripsi_skala' => 'Dapat menggunakan bahasa lisan secara jelas, lancar dan menggunakan Bahasa tulis yang baik dan benar.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 23,
                'skala' => '3',
                'deskripsi_skala' => 'Dapat menggunakan bahasa lisan secara jelas, lancar dan menggunakan Bahasa tulis yang baik dan benar serta memberi motivasi untuk menerapkan bahasa lisan, tulisan yang baik dan benar.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 23,
                'skala' => '4',
                'deskripsi_skala' => 'Dapat menggunakan bahasa lisan secara jelas, lancar dan menggunakan bahasa tulis yang baik dan benar serta memberi motivasi untuk menerapkan bahasa lisan, tulisan yang baik dan benar dengan membuat satu contoh karya tulis.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 24,
                'skala' => '1',
                'deskripsi_skala' => 'Melakukan pengajaran yang mendorong keterampilan literasi murid.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 24,
                'skala' => '2',
                'deskripsi_skala' => 'Melakukan pengajaran yang mendorong keterampilan literasi dan numerasi murid.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 24,
                'skala' => '3',
                'deskripsi_skala' => 'Melakukan pengajaran yang mendorong keterampilan literasi, numerasi dan mendorong siswa untuk membuat proyek hasil karya literasi.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 24,
                'skala' => '4',
                'deskripsi_skala' => 'Melakukan pengajaran dan menerapkan keterampilan literasi, dengan melakukan PTK.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 25,
                'skala' => '1',
                'deskripsi_skala' => 'Memfasilitasi dan membimbing murid merangkum materi pelajaran dalam bentuk penugasan.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 25,
                'skala' => '2',
                'deskripsi_skala' => 'Memfasilitasi dan membimbing murid merangkum materi dalam bentuk penugasan terstruktur.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 25,
                'skala' => '3',
                'deskripsi_skala' => 'Memfasilitasi dan membimbing murid merangkum materi dalam bentuk penugasan terstruktur untuk meningkatkan pengetahuan, keterampilan mengajar.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 25,
                'skala' => '4',
                'deskripsi_skala' => 'Memfasilitasi dan membimbing murid merangkum materi dalam bentuk penugasan terstruktur untuk meningkatkan pengetahuan, keterampilan mengajar, evaluasi dengan memberikan angket penilaian teman sejawat.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 26,
                'skala' => '1',
                'deskripsi_skala' => 'Melaksanakan penilaian produk melalui proyek / hasil produk.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 26,
                'skala' => '2',
                'deskripsi_skala' => 'Melaksanakan penilaian produk melalui proyek / hasil produk dan melaksanakan penilaian pengetahuan melalui tes formatif.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 26,
                'skala' => '3',
                'deskripsi_skala' => 'Melaksanakan penilaian produk melalui proyek / hasil produk, melaksanakan penilaian pengetahuan melalui tes formatif serta penilaian sikap.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 26,
                'skala' => '4',
                'deskripsi_skala' => 'Melaksanakan penilaian produk melalui proyek / hasil produk, melaksanakan penilaian pengetahuan melalui tes formatif serta penilaian sikap yang disajikan dengan rubrik penilaian.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 27,
                'skala' => '1',
                'deskripsi_skala' => 'Dibawah 75%.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 27,
                'skala' => '2',
                'deskripsi_skala' => '75% sampai 85%.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 27,
                'skala' => '3',
                'deskripsi_skala' => '85% sampai dengan 95%.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 27,
                'skala' => '4',
                'deskripsi_skala' => 'Lebih dari 95%.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 28,
                'skala' => '1',
                'deskripsi_skala' => 'Dibawah 75%.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 28,
                'skala' => '2',
                'deskripsi_skala' => '75% sampai 85%.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 28,
                'skala' => '3',
                'deskripsi_skala' => '85% sampai dengan 95%.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 28,
                'skala' => '4',
                'deskripsi_skala' => 'Lebih dari 95%.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 29,
                'skala' => '1',
                'deskripsi_skala' => 'Dibawah 75%.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 29,
                'skala' => '2',
                'deskripsi_skala' => '75% sampai 85%.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 29,
                'skala' => '3',
                'deskripsi_skala' => '85% sampai dengan 95%.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 29,
                'skala' => '4',
                'deskripsi_skala' => 'Lebih dari 95%.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 30,
                'skala' => '1',
                'deskripsi_skala' => 'Dibawah 75%.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 30,
                'skala' => '2',
                'deskripsi_skala' => '75% sampai 85%.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 30,
                'skala' => '3',
                'deskripsi_skala' => '85% sampai dengan 95%.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_skala_indikator' => 30,
                'skala' => '4',
                'deskripsi_skala' => 'Lebih dari 95%.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($skalaIndikatorDetail as $data) {
            \App\Models\SkalaIndikatorDetail::create($data);
        }
    }
}
